#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char* CompileHASM(const char *inputFileContent, const char *outputFileName) {
    if (outputFileName == NULL) {
        printf("Error: Output file name is NULL\n");
        return NULL;
    }

    // Open the output file in write mode
    FILE *outputFile = fopen(outputFileName, "w");
    if (!outputFile) {
        printf("Failed to open the output file: %s\n", outputFileName);
        return NULL;
    }

    // Simulate output generation (normally you'd process the input here)
    const char *output = "Output generated by CompileHASM function.";

    // Print to the output file using fprintf
    fprintf(outputFile, "Processing file: %s\n", outputFileName);
    fprintf(outputFile, "Input File Content: %s\n", inputFileContent);
    fprintf(outputFile, "Output: %s\n", output);

    // Close the file after writing
    fclose(outputFile);

    // Return the generated output string (just for demonstration, though it's written to file)
    size_t outputSize = strlen(output) + 1;  // +1 for null terminator
    char *outputBuffer = (char*)malloc(outputSize);

    if (outputBuffer) {
        strcpy(outputBuffer, output);
    } else {
        printf("Memory allocation failed.\n");
    }

    return outputBuffer;  // Return the output buffer
}

int main() {
    // Just a placeholder for testing
    char *output = CompileHASM("Test Input", "output.txt");
    if (output) {
        printf("Output (printed to file): %s\n", output);
        free(output);  // Remember to free the allocated memory
    } else {
        printf("Failed to compile.\n");
    }
    return 0;
}
